#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("inBeaconSample.Droid.Resource", IsApplication=true)]

namespace inBeaconSample.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int b_car = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int b_compass = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int b_directions = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int b_envelope = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int b_flag = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int b_food = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int b_heart = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int b_idea = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int b_plane = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int b_planet = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int b_present = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int b_radar = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int b_sailingship = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int b_star = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int b_talk = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int b_walkin = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int car = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int compass = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int directions = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int envelope = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int flag = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int food = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int heart = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int icon = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int idea = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int plane = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int planet = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int present = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int proximity = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int radar = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int sailingship = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int star = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int talk = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int walkin = 2130837537;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int webView = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_notify = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int ascendent = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int attention = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int bling = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int boathorn = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int cashregister = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int demonstrative = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int hiccup = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int hit = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int keep = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int littledwarf = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int metal = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int morning = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int oldhorn = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int pop = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int sadtrombone = 2130968590;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
	}
}
#pragma warning restore 1591
